/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ShowcasesRouteImport } from './routes/showcases'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as ComparisonIndexRouteImport } from './routes/comparison.index'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as ComparisonGpuRouteImport } from './routes/comparison.gpu'
import { Route as ComparisonCpuRouteImport } from './routes/comparison.cpu'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesRoute = ShowcasesRouteImport.update({
  id: '/showcases',
  path: '/showcases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackRoute,
} as any)
const ComparisonIndexRoute = ComparisonIndexRouteImport.update({
  id: '/comparison/',
  path: '/comparison/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => TrackRoute,
} as any)
const ComparisonGpuRoute = ComparisonGpuRouteImport.update({
  id: '/comparison/gpu',
  path: '/comparison/gpu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonCpuRoute = ComparisonCpuRouteImport.update({
  id: '/comparison/cpu',
  path: '/comparison/cpu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/showcases': typeof ShowcasesRoute
  '/track': typeof TrackRouteWithChildren
  '/comparison/cpu': typeof ComparisonCpuRoute
  '/comparison/gpu': typeof ComparisonGpuRoute
  '/track/$code': typeof TrackCodeRoute
  '/comparison/': typeof ComparisonIndexRoute
  '/track/': typeof TrackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/showcases': typeof ShowcasesRoute
  '/comparison/cpu': typeof ComparisonCpuRoute
  '/comparison/gpu': typeof ComparisonGpuRoute
  '/track/$code': typeof TrackCodeRoute
  '/comparison': typeof ComparisonIndexRoute
  '/track': typeof TrackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/showcases': typeof ShowcasesRoute
  '/track': typeof TrackRouteWithChildren
  '/comparison/cpu': typeof ComparisonCpuRoute
  '/comparison/gpu': typeof ComparisonGpuRoute
  '/track/$code': typeof TrackCodeRoute
  '/comparison/': typeof ComparisonIndexRoute
  '/track/': typeof TrackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/showcases'
    | '/track'
    | '/comparison/cpu'
    | '/comparison/gpu'
    | '/track/$code'
    | '/comparison/'
    | '/track/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/showcases'
    | '/comparison/cpu'
    | '/comparison/gpu'
    | '/track/$code'
    | '/comparison'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/showcases'
    | '/track'
    | '/comparison/cpu'
    | '/comparison/gpu'
    | '/track/$code'
    | '/comparison/'
    | '/track/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ShowcasesRoute: typeof ShowcasesRoute
  TrackRoute: typeof TrackRouteWithChildren
  ComparisonCpuRoute: typeof ComparisonCpuRoute
  ComparisonGpuRoute: typeof ComparisonGpuRoute
  ComparisonIndexRoute: typeof ComparisonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases': {
      id: '/showcases'
      path: '/showcases'
      fullPath: '/showcases'
      preLoaderRoute: typeof ShowcasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof TrackRoute
    }
    '/comparison/': {
      id: '/comparison/'
      path: '/comparison'
      fullPath: '/comparison/'
      preLoaderRoute: typeof ComparisonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof TrackRoute
    }
    '/comparison/gpu': {
      id: '/comparison/gpu'
      path: '/comparison/gpu'
      fullPath: '/comparison/gpu'
      preLoaderRoute: typeof ComparisonGpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison/cpu': {
      id: '/comparison/cpu'
      path: '/comparison/cpu'
      fullPath: '/comparison/cpu'
      preLoaderRoute: typeof ComparisonCpuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrackRouteChildren {
  TrackCodeRoute: typeof TrackCodeRoute
  TrackIndexRoute: typeof TrackIndexRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackCodeRoute: TrackCodeRoute,
  TrackIndexRoute: TrackIndexRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ShowcasesRoute: ShowcasesRoute,
  TrackRoute: TrackRouteWithChildren,
  ComparisonCpuRoute: ComparisonCpuRoute,
  ComparisonGpuRoute: ComparisonGpuRoute,
  ComparisonIndexRoute: ComparisonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
